//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:		 BSD License
//					 Kratos default license: kratos/license.txt
//
//  Main authors:    Jordi Cotela
//

#include "fluid_dynamics_application_variables.h"

namespace Kratos
{
KRATOS_CREATE_VARIABLE(int,PATCH_INDEX)
KRATOS_CREATE_VARIABLE(double,TAUONE)
KRATOS_CREATE_VARIABLE(double,TAUTWO)
KRATOS_CREATE_VARIABLE(double,PRESSURE_MASSMATRIX_COEFFICIENT)

//KRATOS_CREATE_VARIABLE(double,Y_WALL)
KRATOS_CREATE_VARIABLE(double,SUBSCALE_PRESSURE)
KRATOS_CREATE_VARIABLE(double, C_DES)
//    KRATOS_CREATE_VARIABLE(double, C_SMAGORINSKY)
KRATOS_CREATE_VARIABLE(double, CHARACTERISTIC_VELOCITY)


KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SUBSCALE_VELOCITY)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(COARSE_VELOCITY)

KRATOS_CREATE_VARIABLE(double,FIC_BETA)

// Non-Newtonian constitutive relations
KRATOS_CREATE_VARIABLE(double, REGULARIZATION_COEFFICIENT)

KRATOS_CREATE_VARIABLE(double, BINGHAM_SMOOTHER)
KRATOS_CREATE_VARIABLE(double, GEL_STRENGTH )

// Q-Criterion (for vortex visualization)
KRATOS_CREATE_VARIABLE(double, Q_VALUE)

// Vorticity
KRATOS_CREATE_VARIABLE(double, VORTICITY_MAGNITUDE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(RECOVERED_PRESSURE_GRADIENT)

// For swimming DEM
KRATOS_CREATE_VARIABLE(Vector, NODAL_WEIGHTS)

// Embedded fluid variables
KRATOS_CREATE_VARIABLE(int, EMBEDDED_IS_ACTIVE)
KRATOS_CREATE_VARIABLE(double, EMBEDDED_WET_PRESSURE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(EMBEDDED_WET_VELOCITY)

// Compressible fluid variables
KRATOS_CREATE_VARIABLE(double, HEAT_CAPACITY_RATIO)
KRATOS_CREATE_VARIABLE(double, REACTION_DENSITY)
KRATOS_CREATE_VARIABLE(double, REACTION_ENERGY)
KRATOS_CREATE_VARIABLE(double, MACH)

// Transient adjoint stabilization variable
KRATOS_CREATE_VARIABLE( double, ARTIFICIAL_DIFFUSION)
KRATOS_CREATE_VARIABLE( Matrix, VMS_STEADY_TERM_PRIMAL_GRADIENT_MATRIX)
KRATOS_CREATE_VARIABLE( Matrix, VMS_ADJOINT_ENERGY_GENERATION_RATE_MATRIX)
KRATOS_CREATE_VARIABLE( Matrix, ARTIFICIAL_DIFFUSION_MATRIX)
KRATOS_CREATE_VARIABLE( Matrix, VMS_VELOCITY_GRADIENT_TENSOR)
KRATOS_CREATE_VARIABLE(double ,ADJOINT_ENERGY)
KRATOS_CREATE_VARIABLE(double ,DIFFUSION_ENERGY)

// ------------------- Testing Variables --------------------
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_1_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_2_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_3_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_4_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_5_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_6_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_7_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_8_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_9_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_10_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_11_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_12_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_13_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_14_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_15_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_16_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_17_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_18_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_19_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_20_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_21_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_22_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_23_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_24_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_25_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_26_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_27_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_28_EIGEN_MIN)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_29_EIGEN_MIN)

KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_1_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_2_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_3_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_4_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_5_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_6_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_7_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_8_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_9_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_10_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_11_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_12_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_13_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_14_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_15_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_16_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_17_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_18_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_19_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_20_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_21_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_22_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_23_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_24_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_25_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_26_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_27_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_28_EIGEN_MAX)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_29_EIGEN_MAX)

KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_1_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_2_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_3_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_4_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_5_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_6_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_7_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_8_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_9_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_10_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_11_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_12_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_13_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_14_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_15_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_16_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_17_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_18_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_19_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_20_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_21_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_22_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_23_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_24_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_25_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_26_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_27_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_28_ENERGY)
KRATOS_CREATE_VARIABLE( double, STABILIZATION_ANALYSIS_MATRIX_29_ENERGY)

KRATOS_CREATE_VARIABLE(Matrix, STABILIZATION_ANALYSIS_MATRIX_24)
KRATOS_CREATE_VARIABLE(Matrix, STABILIZATION_ANALYSIS_MATRIX_29)
KRATOS_CREATE_VARIABLE(Matrix, STABILIZATION_ANALYSIS_MATRICES)
}
