#include "compressible_potential_flow_application_variables.h"

namespace Kratos
{
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_INFINITY)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_LOWER)
    KRATOS_CREATE_VARIABLE(double, PRESSURE_LOWER)
    KRATOS_CREATE_VARIABLE(bool, UPPER_SURFACE)
    KRATOS_CREATE_VARIABLE(bool, LOWER_SURFACE)
}
