/*!
* \file   Plasticity.cxx
* \brief  this file implements the Plasticity Behaviour.
*         File generated by tfel version 3.3.0-dev
* \author Helfer Thomas
* \date   23 / 11 / 06
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/PlasticityBehaviourData.hxx"
#include"TFEL/Material/PlasticityIntegrationData.hxx"
#include"TFEL/Material/Plasticity.hxx"

namespace tfel{

namespace material{

PlasticityParametersInitializer&
PlasticityParametersInitializer::get()
{
static PlasticityParametersInitializer i;
return i;
}

PlasticityParametersInitializer::PlasticityParametersInitializer()
{
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.79769e+308;
this->theta = 1;
this->epsilon = 1e-08;
this->iterMax = 100;
// Reading parameters from a file
PlasticityParametersInitializer::readParameters(*this,"Plasticity-parameters.txt");
}

void
PlasticityParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else if(::strcmp("theta",key)==0){
this->theta = v;
} else if(::strcmp("epsilon",key)==0){
this->epsilon = v;
} else {
tfel::raise("PlasticityParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
PlasticityParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
this->iterMax = v;
} else {
tfel::raise("PlasticityParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

double
PlasticityParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"PlasticityParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

unsigned short
PlasticityParametersInitializer::getUnsignedShort(const std::string& n,
const std::string& v)
{
unsigned short value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"PlasticityParametersInitializer::getUnsignedShort: "
"can't convert '"+v+"' to unsigned short for parameter '"+ n+"'");
return value;
}

void
PlasticityParametersInitializer::readParameters(PlasticityParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"PlasticityParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = PlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = PlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("theta"==tokens[0]){
pi.theta = PlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("epsilon"==tokens[0]){
pi.epsilon = PlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("iterMax"==tokens[0]){
pi.iterMax = PlasticityParametersInitializer::getUnsignedShort(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace material

} // end of namespace tfel

